### ISSUE TITLE
Four entries of armor stand in furniture build tab

### ISSUE THREAD

**Issue by torarnv** [ceko/valheim-armorstand#6]
I don't know why, but after enabling and disabling mod a few times in testing, I now have 4 duplicate entries for the stand in the build menu.

**Comment by torarnv** [comment]
I'm assuming there's code missing to reverse what https://github.com/ceko/valheim-armorstand/blob/master/Plugin/ValheimStands/Patches/Pieces.cs#L38 does?

**Comment by ceko** [comment]
Thanks for the report, I'll look into this.

**Comment by ceko** [comment]
I put a simple static flag in when the pieces are added to the hammer prefab for the first time. Shouldn't duplicate now on scene load.

**Comment by torarnv** [comment]
Thanks!
