### ISSUE TITLE
Mod causes blank console

### ISSUE THREAD

**Issue by D-A-R-K-N-E-S-S** [ceko/valheim-armorstand#7]
Someone else created a similar topic but it was closed claiming it had to do with Valheim+.

I don't use Valheim+, only BepInEx. I noticed that the console would go blank and not register any commands. It seems like it would randomly happen when in the same loading area as an armor stand and would it return after I leave the area.

I was easily able to narrow it down to this mod since I am only using 3 mods. I have 8 other users on my dedicated server that experienced the same issue until removing the armorstand mod.

**Comment by ceko** [comment]
This is a problem with the bundled Bepinex used. I'll see about updating it.

**Comment by ceko** [comment]
I updated to the most recent version of BepInEx for Valheim. Console works for me.

**Comment by torarnv** [comment]
Ah, thanks! This was the issue I was investigating when I disabled the mod and lost the stands :)
